name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Enable Debug Mode
      run: set -x  # Enable debug mode to print each command as it runs for easier troubleshooting

    - name: Set up SSH
      env:
        SSH_KEY: ${{ secrets.CPANEL_SSH_KEY }}
      run: |
        # Step 1: Create SSH directory
        mkdir -p ~/.ssh
        echo "Created .ssh directory"
        
        # Step 2: Add SSH private key
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        echo "Added SSH private key to .ssh/id_rsa"
        
        # Step 3: Set permissions for SSH private key
        chmod 600 ~/.ssh/id_rsa
        echo "Set permissions for SSH private key"
        
        # Step 4: Verify the contents of the SSH directory
        ls -la ~/.ssh
        
        # Step 5: Verify the private key file is correctly written (remove this in production for security)
        cat ~/.ssh/id_rsa || echo "Failed to display the private key contents"
      
    - name: Debug CPANEL_HOST
      run: echo "cPanel Host: ${{ secrets.CPANEL_HOST }}"

    - name: Set up known_hosts
      run: |
        # Step to prevent SSH from asking whether to trust the host
        ssh-keyscan -H ${{ secrets.CPANEL_HOST }} >> ~/.ssh/known_hosts
        echo "Added cPanel host to known hosts"

    - name: Deploy Laravel to cPanel
      run: |
        # Step 1: SSH into the cPanel server and navigate to the Laravel directory
        ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && git pull origin main"
        echo "Pulled latest changes from GitHub repository"

        # Step 2: Install Composer dependencies
        ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && composer install --no-dev --optimize-autoloader"
        echo "Installed Composer dependencies"

        # Step 3: Set file permissions for storage and cache
        ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && chmod -R 775 storage bootstrap/cache"
        echo "Set correct file permissions for storage and cache"

        # Step 4: Run Laravel migrations
        ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && php artisan migrate --force"
        echo "Ran database migrations"

        # Step 5: Clear and cache configurations
        ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && php artisan config:cache"
        echo "Cached Laravel configurations"

        # Step 6: Restart services (optional, depends on setup)
        # ssh -i ~/.ssh/id_rsa username@${{ secrets.CPANEL_HOST }} "cd /home/username/public_html && php artisan queue:restart"
        # echo "Restarted Laravel queues"

    - name: Deployment Completed
      run: echo "Deployment to cPanel is complete!"
